site:
  title: "From Metrics to Alerts: Observing AI applications on Red Hat OpenShift AI"
  start_page: rhoai-monitoring-cmo::index.adoc

content:
  sources:
    - url: ./

asciidoc:
  extensions:
    - '@asciidoctor/tabs'
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
